### ISSUE TITLE
Great work!

### ISSUE THREAD

**Issue by Anisha7** [tempor1s/superhero-team-dueler#1]
Great job on your superhero project. Here’s some feedback to improve:
- Run `pytest team_test.py` and fix the typo/syntax errors that come up!
- You can challenge yourself further by attempting a couple of stretch challenges! Try writing your own tests, and/or any of the other interesting game functionalities mentioned in the rubric/class notes.
- I recommend adding a README! Talk about what superhero project is and how to run it.

**Comment by tempor1s** [comment]
Fixed the bug in `team_test.py`, was just an additional space at end of line.  I wrote the entirety of `arena_test.py` as a stretch challenging, learning how to mock inputs and such.  Also the current README has instructions to run the program, but I will add a bit more info on what the project its self actually is.  Thanks for the feedback!
